import re

import numpy as np
import torch

from tts_zs.utils import encoder_uses_e5_prefix

AXES = ("vocoder", "acoustic_model", "arch_family", "speaker_type", "lang_family")

VOCODER_NAME = {
    "hifigan": "HiFi-GAN",
    "bigvgan": "BigVGAN",
    "encodec": "EnCodec",
    "dac": "Descript Audio Codec (DAC)",
    "griffin_lim": "Griffin-Lim",
    "mimi": "Mimi codec",
    "vocos": "Vocos",
    "snac": "SNAC",
    "istft": "iSTFT-based vocoder",
    "wavtokenizer": "WavTokenizer",
    "higgscodec": "Higgs audio codec",
    "locdit": "local diffusion transformer (LocDiT)",
    "ffgan": "Firefly-GAN",
    "nanocodec": "NanoCodec",
    "wavevae": "WaveVAE",
    "bicodec": "BiCodec",
    "xcodec2": "X-Codec 2.0",
    "neucodec": "NeuCodec",
    "proprietary": "proprietary",
    "unknown": "unspecified",
}
ACOUSTIC_NAME = {
    "ar_codec_lm": "autoregressive codec language model",
    "vits": "VITS",
    "encoder_decoder": "encoder-decoder transformer",
    "tacotron": "Tacotron",
    "flow_matching": "flow-matching model",
    "diffusion": "diffusion model",
    "styletts": "StyleTTS",
    "glow": "Glow-TTS",
    "nar_feedforward": "non-autoregressive feed-forward model",
    "proprietary": "proprietary",
}
ARCH_FAMILY_NAME = {
    "codec_ar": "autoregressive codec",
    "vits": "VITS",
    "tortoise_xtts": "Tortoise/XTTS-style",
    "llm_tts": "LLM-based",
    "tacotron": "Tacotron",
    "flow_match": "flow-matching",
    "nar_transformer": "non-autoregressive transformer",
    "diffusion": "diffusion",
    "glow": "Glow-based",
    "multimodal": "multimodal",
    "proprietary": "proprietary",
}
SPEAKER_TYPE_NAME = {
    "zero_shot": "zero-shot voice cloning",
    "multi": "multi-speaker",
    "single": "single-speaker",
    "voice_conv": "voice-conversion",
    "description": "description-prompted",
}
LANG_FAMILY_NAME: dict = {}

NAME_MAP = {
    "vocoder": VOCODER_NAME,
    "acoustic_model": ACOUSTIC_NAME,
    "arch_family": ARCH_FAMILY_NAME,
    "speaker_type": SPEAKER_TYPE_NAME,
    "lang_family": LANG_FAMILY_NAME,
}

_AXIS_FIELD = {
    "vocoder": "vocoder",
    "acoustic_model": "acoustic model",
    "arch_family": "architecture",
    "speaker_type": "speaker configuration",
    "lang_family": "language family",
}

def display_name(axis: str, value: str) -> str:
    return NAME_MAP[axis].get(value, value)

def template_text(axis: str, name: str) -> str:
    return f"This audio was generated by the {name} {_AXIS_FIELD[axis]}."

def template_text_using(axis: str, name: str) -> str:
    return f"This audio was generated using the {name} {_AXIS_FIELD[axis]}."

_VOCODER_TEMPLATES = [
    "This audio was generated by the {name} vocoder.",
    "This audio was generated using the {name} vocoder.",
    "The {name} vocoder was used to synthesise this speech.",
    "{name} produced the waveform in this audio.",
    "This clip uses {name} for waveform generation.",
]
_ACOUSTIC_TEMPLATES = [
    "This audio was generated by the {name} acoustic model.",
    "This audio was generated using the {name} acoustic model.",
    "The {name} acoustic model was used to synthesise this speech.",
    "{name} produced the speech in this audio.",
    "This clip uses {name} as its acoustic model.",
]
_ARCH_FAMILY_TEMPLATES = [
    "This audio was generated by a {name} architecture.",
    "This audio was generated using a {name} architecture.",
    "The {name} architecture was used to synthesise this speech.",
    "{name} is the architecture behind this audio.",
    "This clip was synthesised with a {name} system.",
]
_SPEAKER_TYPE_TEMPLATES = [
    "This audio comes from a {name} text-to-speech system.",
    "This speech was produced by a {name} system.",
    "The synthesiser uses a {name} setup.",
    "{name} synthesis was used for this clip.",
    "This clip was generated in a {name} configuration.",
]
_LANG_FAMILY_TEMPLATES = [
    "This speech belongs to the {name} language family.",
    "The language of this audio is from the {name} family.",
    "This clip is spoken in a {name} language.",
    "This audio uses a language from the {name} family.",
    "The spoken language belongs to {name}.",
]
_AXIS_TEMPLATES = {
    "vocoder": _VOCODER_TEMPLATES,
    "acoustic_model": _ACOUSTIC_TEMPLATES,
    "arch_family": _ARCH_FAMILY_TEMPLATES,
    "speaker_type": _SPEAKER_TYPE_TEMPLATES,
    "lang_family": _LANG_FAMILY_TEMPLATES,
}

def _fix_article(s: str) -> str:
    return re.sub(
        r"\b([Aa]) ([aeiouAEIOU])",
        lambda m: ("an" if m.group(1) == "a" else "An") + " " + m.group(2),
        s,
    )

def template_variants(axis: str, name: str) -> list[str]:
    return [_fix_article(t.format(name=name)) for t in _AXIS_TEMPLATES[axis]]

def encode_value_templates(
    values: list[str], axis: str, encoder: str, device, prefix: str = "passage"
) -> torch.Tensor:
    from sentence_transformers import SentenceTransformer

    strings = [template_text(axis, display_name(axis, v)) for v in values]
    if encoder_uses_e5_prefix(encoder):
        strings = [f"{prefix}: {s}" for s in strings]
    st = SentenceTransformer(encoder, trust_remote_code=True)
    embs = st.encode(
        strings,
        batch_size=32,
        show_progress_bar=False,
        normalize_embeddings=True,
        convert_to_numpy=True,
    )
    return torch.from_numpy(embs.astype(np.float32)).to(device)
